import type {
  ChangeOrder,
  Delivery,
  DrawingSet,
  DrawingSheet,
  FabItem,
  InstallItem,
  Project,
  Rfi,
  Task,
} from "./types";

export const SEED_PROJECTS: Project[] = [
  {
    id: "p1",
    code: "PHX-2401",
    name: "Phoenix Logistics Hub",
    client: "Desert Logistics LLC",
    status: "Active",
    startDate: "2026-03-15",
    targetComplete: "2026-09-30",
    owner: "Nick L.",
    notes: "AISC fab + erect",
  },
  {
    id: "p2",
    code: "TUC-2408",
    name: "Tucson Medical Expansion",
    client: "Banner Health",
    status: "Active",
    startDate: "2026-05-01",
    targetComplete: "2026-11-15",
    owner: "Nick L.",
    notes: "Misc steel + joists",
  },
];

export const SEED_DRAWING_SETS: DrawingSet[] = [
  {
    id: "ds1",
    projectId: "p1",
    name: "Structural IFC — Foundations",
    type: "Structural",
    description: "Foundation & embed package",
    submitted: "2026-07-10",
    requiredBy: "2026-07-20",
    status: "Approved",
    ballInCourt: "Closed",
    owner: "Nick L.",
    notes: "IFC approved",
  },
  {
    id: "ds2",
    projectId: "p1",
    name: "Structural IFC — Main Frame",
    type: "Structural",
    description: "Columns, beams, braces",
    submitted: "2026-07-22",
    requiredBy: "2026-08-01",
    status: "Under Review",
    ballInCourt: "GC",
    owner: "Nick L.",
    notes: "Waiting SE stamp",
  },
  {
    id: "ds3",
    projectId: "p2",
    name: "General Notes & Specs",
    type: "Structural",
    description: "Project notes package",
    submitted: "2026-07-15",
    requiredBy: "2026-07-25",
    status: "Approved as Noted",
    ballInCourt: "Closed",
    owner: "Nick L.",
    notes: "Minor markups",
  },
  {
    id: "ds4",
    projectId: "p2",
    name: "Joist & Deck Layout",
    type: "Structural",
    description: "Joist seats + deck",
    submitted: "",
    requiredBy: "2026-08-05",
    status: "Not Submitted",
    ballInCourt: "Shop",
    owner: "Nick L.",
    notes: "Pending final loads",
  },
];

export const SEED_DRAWING_SHEETS: DrawingSheet[] = [
  {
    id: "sh1",
    setId: "ds1",
    numberRev: "S-101 Rev A",
    description: "Foundation Plan",
    submitted: "2026-07-10",
    requiredBy: "2026-07-20",
    status: "Approved",
    ballInCourt: "Closed",
    notes: "",
  },
  {
    id: "sh2",
    setId: "ds1",
    numberRev: "S-102 Rev A",
    description: "Embed Schedule",
    submitted: "2026-07-10",
    requiredBy: "2026-07-20",
    status: "Approved",
    ballInCourt: "Closed",
    notes: "",
  },
  {
    id: "sh3",
    setId: "ds1",
    numberRev: "S-103 Rev 0",
    description: "Anchor Bolt Plan",
    submitted: "2026-07-10",
    requiredBy: "2026-07-20",
    status: "Approved as Noted",
    ballInCourt: "Closed",
    notes: "Projection note",
  },
  {
    id: "sh4",
    setId: "ds2",
    numberRev: "S-201 Rev B",
    description: "Main Frame Elev — Grid A",
    submitted: "2026-07-22",
    requiredBy: "2026-08-01",
    status: "Under Review",
    ballInCourt: "SE",
    notes: "",
  },
  {
    id: "sh5",
    setId: "ds2",
    numberRev: "S-202 Rev B",
    description: "Main Frame Elev — Grid B",
    submitted: "2026-07-22",
    requiredBy: "2026-08-01",
    status: "Under Review",
    ballInCourt: "SE",
    notes: "",
  },
  {
    id: "sh6",
    setId: "ds2",
    numberRev: "S-210 Rev A",
    description: "Connection Details",
    submitted: "2026-07-22",
    requiredBy: "2026-08-04",
    status: "Submitted",
    ballInCourt: "GC",
    notes: "Moment @ Grid B",
  },
  {
    id: "sh7",
    setId: "ds3",
    numberRev: "S-001 Rev 0",
    description: "General Notes",
    submitted: "2026-07-15",
    requiredBy: "2026-07-25",
    status: "Approved as Noted",
    ballInCourt: "Closed",
    notes: "",
  },
  {
    id: "sh8",
    setId: "ds3",
    numberRev: "S-002 Rev 0",
    description: "Typical Details",
    submitted: "2026-07-15",
    requiredBy: "2026-07-25",
    status: "Approved",
    ballInCourt: "Closed",
    notes: "",
  },
  {
    id: "sh9",
    setId: "ds4",
    numberRev: "S-301 Rev A",
    description: "Joist Layout Plan",
    submitted: "",
    requiredBy: "2026-08-05",
    status: "Not Submitted",
    ballInCourt: "Shop",
    notes: "Pending loads",
  },
  {
    id: "sh10",
    setId: "ds4",
    numberRev: "S-302 Rev 0",
    description: "Joist Seat Schedule",
    submitted: "",
    requiredBy: "2026-08-05",
    status: "Not Submitted",
    ballInCourt: "Shop",
    notes: "",
  },
  {
    id: "sh11",
    setId: "ds4",
    numberRev: "S-310 Rev 0",
    description: "Deck Plan",
    submitted: "",
    requiredBy: "2026-08-06",
    status: "Not Submitted",
    ballInCourt: "Detailer",
    notes: "",
  },
];

export const SEED_FAB: FabItem[] = [
  {
    id: "f1",
    projectId: "p1",
    workPackage: "WP-01 Columns Area A",
    description: "Main columns Grid 1–4",
    qty: 12,
    weightTons: 18.6,
    drawingRef: "S-201",
    status: "Welded",
    pctComplete: 75,
    shop: "Main Shop",
    plannedDate: "2026-08-04",
    owner: "Shop Lead",
    notes: "",
  },
  {
    id: "f2",
    projectId: "p1",
    workPackage: "WP-02 Beams Area A",
    description: "Floor & roof beams",
    qty: 36,
    weightTons: 22.4,
    drawingRef: "S-201 / S-202",
    status: "Fitted",
    pctComplete: 50,
    shop: "Main Shop",
    plannedDate: "2026-08-06",
    owner: "Shop Lead",
    notes: "",
  },
  {
    id: "f3",
    projectId: "p1",
    workPackage: "WP-03 Bracing & Misc",
    description: "Vertical braces + connection plates",
    qty: 48,
    weightTons: 6.1,
    drawingRef: "S-210",
    status: "Cut",
    pctComplete: 20,
    shop: "Main Shop",
    plannedDate: "2026-08-08",
    owner: "Shop Lead",
    notes: "",
  },
  {
    id: "f4",
    projectId: "p2",
    workPackage: "WP-10 Joists Wing B",
    description: "Open-web joists Level 2",
    qty: 24,
    weightTons: 3.2,
    drawingRef: "S-301",
    status: "Released",
    pctComplete: 5,
    shop: "Joist Bay",
    plannedDate: "2026-08-10",
    owner: "Shop Lead",
    notes: "Awaiting steel",
  },
];

export const SEED_DELIVERY: Delivery[] = [
  {
    id: "dl1",
    projectId: "p1",
    loadNumber: "T-2401-01",
    pieceMarks: "WP-01, WP-02",
    plannedShip: "2026-08-05",
    actualShip: "",
    plannedArrival: "2026-08-06",
    actualArrival: "",
    status: "Scheduled",
    destination: "Site PHX",
    owner: "Nick L.",
    notes: "",
  },
  {
    id: "dl2",
    projectId: "p1",
    loadNumber: "T-2401-02",
    pieceMarks: "WP-03",
    plannedShip: "2026-08-09",
    actualShip: "",
    plannedArrival: "2026-08-10",
    actualArrival: "",
    status: "Scheduled",
    destination: "Site PHX",
    owner: "Nick L.",
    notes: "",
  },
  {
    id: "dl3",
    projectId: "p2",
    loadNumber: "T-2408-01",
    pieceMarks: "WP-10",
    plannedShip: "2026-08-12",
    actualShip: "",
    plannedArrival: "2026-08-13",
    actualArrival: "",
    status: "Scheduled",
    destination: "Site TUC",
    owner: "Nick L.",
    notes: "",
  },
];

export const SEED_INSTALL: InstallItem[] = [
  {
    id: "i1",
    projectId: "p1",
    sequenceArea: "Area A - Grid 1-4",
    pieceMarks: "WP-01",
    plannedErect: "2026-08-07",
    status: "On Site",
    pctComplete: 10,
    crew: "Crew 1",
    owner: "Nick L.",
    notes: "",
  },
  {
    id: "i2",
    projectId: "p1",
    sequenceArea: "Area A - Grid 1-4",
    pieceMarks: "WP-02",
    plannedErect: "2026-08-08",
    status: "Staged",
    pctComplete: 0,
    crew: "Crew 1",
    owner: "Nick L.",
    notes: "",
  },
  {
    id: "i3",
    projectId: "p2",
    sequenceArea: "Wing B - Level 2",
    pieceMarks: "WP-10",
    plannedErect: "2026-08-15",
    status: "On Site",
    pctComplete: 0,
    crew: "Crew 2",
    owner: "Nick L.",
    notes: "Awaiting deck",
  },
];

export const SEED_RFIS: Rfi[] = [
  {
    id: "r1",
    projectId: "p1",
    rfiNumber: "RFI-012",
    subject: "Anchor bolt projection conflict",
    issued: "2026-07-28",
    responseDue: "2026-08-04",
    status: "Open",
    ballInCourt: "SE",
    impact: "Possible 2-day delay",
    linkedDrawing: "S-103",
    notes: "Need revised detail",
  },
  {
    id: "r2",
    projectId: "p1",
    rfiNumber: "RFI-013",
    subject: "Beam penetration clearance",
    issued: "2026-07-30",
    responseDue: "2026-08-06",
    status: "Open",
    ballInCourt: "Architect",
    impact: "None expected",
    linkedDrawing: "S-201",
    notes: "",
  },
  {
    id: "r3",
    projectId: "p2",
    rfiNumber: "RFI-005",
    subject: "Joist seat elevation",
    issued: "2026-07-20",
    responseDue: "2026-07-27",
    status: "Answered",
    ballInCourt: "Closed",
    impact: "None",
    linkedDrawing: "S-302",
    notes: "Clarified",
  },
];

export const SEED_COS: ChangeOrder[] = [
  {
    id: "c1",
    projectId: "p1",
    coNumber: "CO-003",
    description: "Add moment connection at Grid B",
    linked: "RFI-012 / S-210",
    cost: 28500,
    scheduleDays: 3,
    status: "Submitted",
    owner: "Nick L.",
    notes: "Pending GC review",
  },
  {
    id: "c2",
    projectId: "p2",
    coNumber: "CO-001",
    description: "Revised joist seats",
    linked: "RFI-005",
    cost: 19700,
    scheduleDays: 1,
    status: "Approved",
    owner: "Nick L.",
    notes: "Implemented in fab",
  },
];

export const SEED_TASKS: Task[] = [
  {
    id: "t1",
    projectId: "p1",
    task: "Submit mill certs for WP-01",
    category: "QC",
    owner: "Shop Lead",
    due: "2026-08-04",
    status: "In Progress",
    priority: "High",
    notes: "",
  },
  {
    id: "t2",
    projectId: "p1",
    task: "Confirm crane availability",
    category: "Logistics",
    owner: "Nick L.",
    due: "2026-08-05",
    status: "Not Started",
    priority: "High",
    notes: "",
  },
  {
    id: "t3",
    projectId: "p2",
    task: "Update BIM model with RFI-005",
    category: "Engineering",
    owner: "Detailer",
    due: "2026-08-03",
    status: "Complete",
    priority: "Med",
    notes: "",
  },
  {
    id: "t4",
    projectId: "p1",
    task: "Field measure Grid A embeds",
    category: "Field",
    owner: "Crew 1",
    due: "2026-08-06",
    status: "Not Started",
    priority: "Med",
    notes: "",
  },
];
