import type {
  ChangeOrder,
  Delivery,
  DrawingSet,
  DrawingSheet,
  FabItem,
  InstallItem,
  JournalEntry,
  Project,
  Rfi,
  Roadblock,
  Submittal,
  Task,
  WorkPackage,
} from "./types";

export const SEED_PROJECTS: Project[] = [
  {
    id: "p1",
    code: "PHX-2401",
    name: "Phoenix Logistics Hub",
    client: "Desert Logistics LLC",
    status: "Active",
    startDate: "2026-03-15",
    targetComplete: "2026-09-30",
    owner: "Nick L.",
    notes: "AISC fab + erect",
  },
  {
    id: "p2",
    code: "TUC-2408",
    name: "Tucson Medical Expansion",
    client: "Banner Health",
    status: "Active",
    startDate: "2026-05-01",
    targetComplete: "2026-11-15",
    owner: "Nick L.",
    notes: "Misc steel + joists",
  },
];

export const SEED_DRAWING_SETS: DrawingSet[] = [
  {
    id: "ds1",
    projectId: "p1",
    name: "Structural IFC — Foundations",
    type: "Structural",
    description: "Foundation & embed package",
    submitted: "2026-07-10",
    requiredBy: "2026-07-20",
    status: "Approved",
    ballInCourt: "Closed",
    owner: "Nick L.",
    notes: "IFC approved",
  },
  {
    id: "ds2",
    projectId: "p1",
    name: "Structural IFC — Main Frame",
    type: "Structural",
    description: "Columns, beams, braces",
    submitted: "2026-07-22",
    requiredBy: "2026-08-01",
    status: "Under Review",
    ballInCourt: "GC",
    owner: "Nick L.",
    notes: "Waiting SE stamp",
  },
  {
    id: "ds3",
    projectId: "p2",
    name: "General Notes & Specs",
    type: "Structural",
    description: "Project notes package",
    submitted: "2026-07-15",
    requiredBy: "2026-07-25",
    status: "Approved as Noted",
    ballInCourt: "Closed",
    owner: "Nick L.",
    notes: "Minor markups",
  },
  {
    id: "ds4",
    projectId: "p2",
    name: "Joist & Deck Layout",
    type: "Structural",
    description: "Joist seats + deck",
    submitted: "",
    requiredBy: "2026-08-05",
    status: "Not Submitted",
    ballInCourt: "Shop",
    owner: "Nick L.",
    notes: "Pending final loads",
  },
];

export const SEED_DRAWING_SHEETS: DrawingSheet[] = [
  {
    id: "sh1",
    setId: "ds1",
    numberRev: "S-101 Rev A",
    description: "Foundation Plan",
    submitted: "2026-07-10",
    requiredBy: "2026-07-20",
    status: "Approved",
    ballInCourt: "Closed",
    notes: "",
  },
  {
    id: "sh2",
    setId: "ds1",
    numberRev: "S-102 Rev A",
    description: "Embed Schedule",
    submitted: "2026-07-10",
    requiredBy: "2026-07-20",
    status: "Approved",
    ballInCourt: "Closed",
    notes: "",
  },
  {
    id: "sh3",
    setId: "ds1",
    numberRev: "S-103 Rev 0",
    description: "Anchor Bolt Plan",
    submitted: "2026-07-10",
    requiredBy: "2026-07-20",
    status: "Approved as Noted",
    ballInCourt: "Closed",
    notes: "Projection note",
  },
  {
    id: "sh4",
    setId: "ds2",
    numberRev: "S-201 Rev B",
    description: "Main Frame Elev — Grid A",
    submitted: "2026-07-22",
    requiredBy: "2026-08-01",
    status: "Under Review",
    ballInCourt: "SE",
    notes: "",
  },
  {
    id: "sh5",
    setId: "ds2",
    numberRev: "S-202 Rev B",
    description: "Main Frame Elev — Grid B",
    submitted: "2026-07-22",
    requiredBy: "2026-08-01",
    status: "Under Review",
    ballInCourt: "SE",
    notes: "",
  },
  {
    id: "sh6",
    setId: "ds2",
    numberRev: "S-210 Rev A",
    description: "Connection Details",
    submitted: "2026-07-22",
    requiredBy: "2026-08-04",
    status: "Submitted",
    ballInCourt: "GC",
    notes: "Moment @ Grid B",
  },
  {
    id: "sh7",
    setId: "ds3",
    numberRev: "S-001 Rev 0",
    description: "General Notes",
    submitted: "2026-07-15",
    requiredBy: "2026-07-25",
    status: "Approved as Noted",
    ballInCourt: "Closed",
    notes: "",
  },
  {
    id: "sh8",
    setId: "ds3",
    numberRev: "S-002 Rev 0",
    description: "Typical Details",
    submitted: "2026-07-15",
    requiredBy: "2026-07-25",
    status: "Approved",
    ballInCourt: "Closed",
    notes: "",
  },
  {
    id: "sh9",
    setId: "ds4",
    numberRev: "S-301 Rev A",
    description: "Joist Layout Plan",
    submitted: "",
    requiredBy: "2026-08-05",
    status: "Not Submitted",
    ballInCourt: "Shop",
    notes: "Pending loads",
  },
  {
    id: "sh10",
    setId: "ds4",
    numberRev: "S-302 Rev 0",
    description: "Joist Seat Schedule",
    submitted: "",
    requiredBy: "2026-08-05",
    status: "Not Submitted",
    ballInCourt: "Shop",
    notes: "",
  },
  {
    id: "sh11",
    setId: "ds4",
    numberRev: "S-310 Rev 0",
    description: "Deck Plan",
    submitted: "",
    requiredBy: "2026-08-06",
    status: "Not Submitted",
    ballInCourt: "Detailer",
    notes: "",
  },
];

export const SEED_WORK_PACKAGES: WorkPackage[] = [
  {
    id: "wp1",
    projectId: "p1",
    code: "WP-01",
    name: "Columns Area A",
    description: "Main columns Grid 1–4",
    status: "In Fabrication",
    plannedStart: "2026-07-25",
    plannedComplete: "2026-08-04",
    tonnage: 18.6,
    owner: "Shop Lead",
    notes: "",
  },
  {
    id: "wp2",
    projectId: "p1",
    code: "WP-02",
    name: "Beams Area A",
    description: "Floor & roof beams",
    status: "In Fabrication",
    plannedStart: "2026-07-28",
    plannedComplete: "2026-08-06",
    tonnage: 22.4,
    owner: "Shop Lead",
    notes: "",
  },
  {
    id: "wp3",
    projectId: "p1",
    code: "WP-03",
    name: "Bracing & Misc",
    description: "Vertical braces + connection plates",
    status: "Released",
    plannedStart: "2026-07-30",
    plannedComplete: "2026-08-08",
    tonnage: 6.1,
    owner: "Shop Lead",
    notes: "",
  },
  {
    id: "wp10",
    projectId: "p2",
    code: "WP-10",
    name: "Joists Wing B",
    description: "Open-web joists Level 2",
    status: "Planned",
    plannedStart: "2026-08-01",
    plannedComplete: "2026-08-10",
    tonnage: 3.2,
    owner: "Shop Lead",
    notes: "Awaiting steel",
  },
];

export const SEED_FAB: FabItem[] = [
  {
    id: "f1",
    projectId: "p1",
    workPackage: "WP-01 Columns Area A",
    workPackageId: "wp1",
    description: "Main columns Grid 1–4",
    qty: 12,
    weightTons: 18.6,
    drawingRef: "S-201",
    status: "Welded",
    pctComplete: 75,
    shop: "Main Shop",
    plannedDate: "2026-08-04",
    owner: "Shop Lead",
    notes: "",
  },
  {
    id: "f2",
    projectId: "p1",
    workPackage: "WP-02 Beams Area A",
    workPackageId: "wp2",
    description: "Floor & roof beams",
    qty: 36,
    weightTons: 22.4,
    drawingRef: "S-201 / S-202",
    status: "Fitted",
    pctComplete: 50,
    shop: "Main Shop",
    plannedDate: "2026-08-06",
    owner: "Shop Lead",
    notes: "",
  },
  {
    id: "f3",
    projectId: "p1",
    workPackage: "WP-03 Bracing & Misc",
    workPackageId: "wp3",
    description: "Vertical braces + connection plates",
    qty: 48,
    weightTons: 6.1,
    drawingRef: "S-210",
    status: "Cut",
    pctComplete: 20,
    shop: "Main Shop",
    plannedDate: "2026-08-08",
    owner: "Shop Lead",
    notes: "",
  },
  {
    id: "f4",
    projectId: "p2",
    workPackage: "WP-10 Joists Wing B",
    workPackageId: "wp10",
    description: "Open-web joists Level 2",
    qty: 24,
    weightTons: 3.2,
    drawingRef: "S-301",
    status: "Released",
    pctComplete: 5,
    shop: "Joist Bay",
    plannedDate: "2026-08-10",
    owner: "Shop Lead",
    notes: "Awaiting steel",
  },
];

export const SEED_DELIVERY: Delivery[] = [
  {
    id: "dl1",
    projectId: "p1",
    loadNumber: "T-2401-01",
    pieceMarks: "WP-01, WP-02",
    plannedShip: "2026-08-05",
    actualShip: "",
    plannedArrival: "2026-08-06",
    actualArrival: "",
    status: "Scheduled",
    destination: "Site PHX",
    owner: "Nick L.",
    notes: "",
  },
  {
    id: "dl2",
    projectId: "p1",
    loadNumber: "T-2401-02",
    workPackageId: "wp3",
    pieceMarks: "WP-03",
    plannedShip: "2026-08-09",
    actualShip: "",
    plannedArrival: "2026-08-10",
    actualArrival: "",
    status: "Scheduled",
    destination: "Site PHX",
    owner: "Nick L.",
    notes: "",
  },
  {
    id: "dl3",
    projectId: "p2",
    loadNumber: "T-2408-01",
    workPackageId: "wp10",
    pieceMarks: "WP-10",
    plannedShip: "2026-08-12",
    actualShip: "",
    plannedArrival: "2026-08-13",
    actualArrival: "",
    status: "Scheduled",
    destination: "Site TUC",
    owner: "Nick L.",
    notes: "",
  },
];

export const SEED_INSTALL: InstallItem[] = [
  {
    id: "i1",
    projectId: "p1",
    workPackageId: "wp1",
    sequenceArea: "Area A - Grid 1-4",
    pieceMarks: "WP-01",
    plannedErect: "2026-08-07",
    status: "On Site",
    pctComplete: 10,
    crew: "Crew 1",
    owner: "Nick L.",
    notes: "",
  },
  {
    id: "i2",
    projectId: "p1",
    workPackageId: "wp2",
    sequenceArea: "Area A - Grid 1-4",
    pieceMarks: "WP-02",
    plannedErect: "2026-08-08",
    status: "Staged",
    pctComplete: 0,
    crew: "Crew 1",
    owner: "Nick L.",
    notes: "",
  },
  {
    id: "i3",
    projectId: "p2",
    sequenceArea: "Wing B - Level 2",
    pieceMarks: "WP-10",
    plannedErect: "2026-08-15",
    status: "On Site",
    pctComplete: 0,
    crew: "Crew 2",
    owner: "Nick L.",
    notes: "Awaiting deck",
  },
];

export const SEED_RFIS: Rfi[] = [
  {
    id: "r1",
    projectId: "p1",
    rfiNumber: "RFI-012",
    subject: "Anchor bolt projection conflict",
    issued: "2026-07-28",
    responseDue: "2026-08-04",
    status: "Open",
    ballInCourt: "SE",
    impact: "Possible 2-day delay",
    linkedDrawing: "S-103",
    notes: "Need revised detail",
  },
  {
    id: "r2",
    projectId: "p1",
    rfiNumber: "RFI-013",
    subject: "Beam penetration clearance",
    issued: "2026-07-30",
    responseDue: "2026-08-06",
    status: "Open",
    ballInCourt: "Architect",
    impact: "None expected",
    linkedDrawing: "S-201",
    notes: "",
  },
  {
    id: "r3",
    projectId: "p2",
    rfiNumber: "RFI-005",
    subject: "Joist seat elevation",
    issued: "2026-07-20",
    responseDue: "2026-07-27",
    status: "Answered",
    ballInCourt: "Closed",
    impact: "None",
    linkedDrawing: "S-302",
    notes: "Clarified",
  },
];

export const SEED_COS: ChangeOrder[] = [
  {
    id: "c1",
    projectId: "p1",
    coNumber: "CO-003",
    description: "Add moment connection at Grid B",
    linked: "RFI-012 / S-210",
    cost: 28500,
    scheduleDays: 3,
    status: "Submitted",
    submitted: "2026-07-29",
    decisionDue: "2026-08-05",
    owner: "Nick L.",
    notes: "Pending GC review — drives the Grid B release to the shop.",
  },
  {
    id: "c2",
    projectId: "p2",
    coNumber: "CO-001",
    description: "Revised joist seats",
    linked: "RFI-005",
    cost: 19700,
    scheduleDays: 1,
    status: "Approved",
    submitted: "2026-07-10",
    decisionDue: "2026-07-24",
    owner: "Nick L.",
    notes: "Implemented in fab",
  },
  {
    id: "c3",
    projectId: "p2",
    coNumber: "CO-004",
    description: "Added canopy bridging per R&R comments",
    linked: "SUB-101",
    cost: 7400,
    scheduleDays: 2,
    status: "Under Review",
    submitted: "2026-07-24",
    decisionDue: "2026-07-31",
    owner: "Nick L.",
    notes: "Overdue for a decision — joist release is waiting on it.",
  },
];

export const SEED_TASKS: Task[] = [
  {
    id: "t1",
    projectId: "p1",
    task: "Submit mill certs for WP-01",
    category: "QC",
    owner: "Shop Lead",
    due: "2026-08-04",
    status: "In Progress",
    priority: "High",
    notes: "",
  },
  {
    id: "t2",
    projectId: "p1",
    task: "Confirm crane availability",
    category: "Logistics",
    owner: "Nick L.",
    due: "2026-08-05",
    status: "Not Started",
    priority: "High",
    notes: "",
  },
  {
    id: "t3",
    projectId: "p2",
    task: "Update BIM model with RFI-005",
    category: "Engineering",
    owner: "Detailer",
    due: "2026-08-03",
    status: "Complete",
    priority: "Med",
    notes: "",
  },
  {
    id: "t4",
    projectId: "p1",
    task: "Field measure Grid A embeds",
    category: "Field",
    owner: "Crew 1",
    due: "2026-08-06",
    status: "Not Started",
    priority: "Med",
    notes: "",
  },
];

export const SEED_ROADBLOCKS: Roadblock[] = [
  {
    id: "rb1",
    projectId: "p1",
    title: "Anchor bolt conflict holding foundation pour",
    category: "RFI",
    description: "RFI-012 response pending; GC will not release pour until resolved",
    raisedDate: "2026-07-29",
    ballInCourt: "SE",
    impact: "Schedule",
    severity: "High",
    status: "Open",
    resolvedDate: "",
    linkedEntityType: "rfi",
    linkedEntityId: "r1",
    owner: "Nick L.",
    notes: "Escalate if no answer by 8/4",
  },
  {
    id: "rb2",
    projectId: "p2",
    title: "Joist supplier lead time slip",
    category: "Procurement",
    description: "Steel mill pushed WP-10 release 5 business days",
    raisedDate: "2026-07-30",
    ballInCourt: "Supplier",
    impact: "Schedule",
    severity: "Med",
    status: "Open",
    resolvedDate: "",
    linkedEntityType: "workPackage",
    linkedEntityId: "wp10",
    owner: "Nick L.",
    notes: "Chasing revised mill cert date",
  },
  {
    id: "rb3",
    projectId: "p1",
    title: "Grid B moment connection scope gap",
    category: "ChangeOrder",
    description: "CO-003 pending GC approval before shop can release detail",
    raisedDate: "2026-07-25",
    ballInCourt: "GC",
    impact: "Cost",
    severity: "Med",
    status: "Resolved",
    resolvedDate: "2026-07-31",
    linkedEntityType: "changeOrder",
    linkedEntityId: "c1",
    owner: "Nick L.",
    notes: "Approved verbally, written CO to follow",
  },
];


/**
 * Submittal register. Note these ride alongside the drawing sets rather than
 * duplicating them: SUB-001 is the transmittal that carried the PHX Sequence 1
 * shop drawing set out the door, so its `linkedDrawingSet` points back at it.
 */
export const SEED_SUBMITTALS: Submittal[] = [
  {
    id: "sb1",
    projectId: "p1",
    submittalNumber: "SUB-001",
    type: "Shop Drawings",
    title: "Sequence 1 — main frame shop drawings",
    specSection: "05 12 00",
    revision: "1",
    submitted: "2026-06-12",
    dueBack: "2026-06-26",
    returned: "2026-06-24",
    status: "Approved as Noted",
    ballInCourt: "Us",
    linkedDrawingSet: "PHX Seq 1",
    owner: "Nick L.",
    notes: "Back with comments on brace gussets — incorporated in Rev 1.",
  },
  {
    id: "sb2",
    projectId: "p1",
    submittalNumber: "SUB-002",
    type: "Anchor Bolt Plan",
    title: "AB setting plan — grids A–F",
    specSection: "05 12 00",
    revision: "0",
    submitted: "2026-05-20",
    dueBack: "2026-06-03",
    returned: "2026-05-29",
    status: "Approved",
    ballInCourt: "Us",
    linkedDrawingSet: "PHX AB Plan",
    owner: "Nick L.",
    notes: "Released to GC for layout.",
  },
  {
    id: "sb3",
    projectId: "p1",
    submittalNumber: "SUB-006",
    type: "Paint / Coating",
    title: "Shop primer + intermediate coat product data",
    specSection: "09 91 00",
    revision: "0",
    submitted: "2026-07-30",
    dueBack: "2026-08-13",
    returned: "",
    status: "Under Review",
    ballInCourt: "Architect",
    linkedDrawingSet: "",
    owner: "Nick L.",
    notes: "Architect wants a color chip before signing off. Chase 8/6.",
  },
  {
    id: "sb4",
    projectId: "p1",
    submittalNumber: "SUB-007",
    type: "Welder Quals",
    title: "Welder continuity + WPS package",
    specSection: "05 05 23",
    revision: "0",
    submitted: "2026-08-01",
    dueBack: "2026-08-08",
    returned: "",
    status: "Submitted",
    ballInCourt: "EOR",
    linkedDrawingSet: "",
    owner: "Shop QC",
    notes: "Two new welders added — continuity logs attached.",
  },
  {
    id: "sb5",
    projectId: "p2",
    submittalNumber: "SUB-101",
    type: "Joists / Girders",
    title: "OWSJ + joist girder package (Vulcraft)",
    specSection: "05 21 00",
    revision: "0",
    submitted: "2026-07-15",
    dueBack: "2026-07-29",
    returned: "2026-08-02",
    status: "Revise & Resubmit",
    ballInCourt: "Us",
    linkedDrawingSet: "",
    owner: "Nick L.",
    notes: "R&R: bridging not shown at canopy. Resubmit due 8/10 — drives joist release.",
  },
  {
    id: "sb6",
    projectId: "p2",
    submittalNumber: "SUB-104",
    type: "Mill Certs",
    title: "Mill test reports — W-shapes heat lot 4412",
    specSection: "05 12 00",
    revision: "0",
    submitted: "",
    dueBack: "2026-08-07",
    returned: "",
    status: "Not Submitted",
    ballInCourt: "Us",
    linkedDrawingSet: "",
    owner: "Purchasing",
    notes: "Waiting on service center to forward certs.",
  },
  {
    id: "sb7",
    projectId: "p2",
    submittalNumber: "SUB-106",
    type: "Erection Plan",
    title: "Erection sequence + crane pick plan",
    specSection: "01 33 00",
    revision: "0",
    submitted: "2026-08-02",
    dueBack: "2026-08-16",
    returned: "",
    status: "Submitted",
    ballInCourt: "GC",
    linkedDrawingSet: "",
    owner: "Nick L.",
    notes: "Needs GC sign-off before mobilization.",
  },
];

/** Daily field journal — the erection-side record behind delay and CO claims. */
export const SEED_JOURNAL: JournalEntry[] = [
  {
    id: "j1",
    projectId: "p1",
    entryDate: "2026-08-01",
    weather: "Clear, light wind",
    tempHigh: 106,
    crewCount: 6,
    manhours: 54,
    tonsErected: 18.5,
    workPerformed: "Set columns A1–D4, plumbed and bolted bay 1–2. Began perimeter beams line A.",
    delays: "",
    deliveriesReceived: "LD-004 — 12 columns, 8 beams. Count verified against BOL.",
    visitors: "GC super walked bay 1 at 10:00.",
    safetyNotes: "Heat plan in effect — rotating breaks every hour after 11:00.",
    author: "Nick L.",
  },
  {
    id: "j2",
    projectId: "p1",
    entryDate: "2026-07-31",
    weather: "Overcast, monsoon cell PM",
    tempHigh: 99,
    crewCount: 6,
    manhours: 38,
    tonsErected: 9.2,
    workPerformed: "Continued bay 1 columns. Shook out LD-003.",
    delays: "Crane down 2.5 hrs — lightning within 5 mi, crew off steel per policy.",
    deliveriesReceived: "LD-003 — braces and misc.",
    visitors: "",
    safetyNotes: "Lightning hold called at 13:20, released 15:50.",
    author: "Nick L.",
  },
  {
    id: "j3",
    projectId: "p2",
    entryDate: "2026-08-01",
    weather: "Clear",
    tempHigh: 101,
    crewCount: 4,
    manhours: 32,
    tonsErected: 0,
    workPerformed: "Anchor bolt survey with GC. Documented 3 AB locations out of tolerance at grid C.",
    delays: "Cannot set grid C columns until AB fix is resolved — see RFI.",
    deliveriesReceived: "",
    visitors: "EOR field rep on site 09:00–11:00.",
    safetyNotes: "No incidents.",
    author: "Nick L.",
  },
];
