/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DrawingsRouteImport } from './routes/drawings'
import { Route as FabricationRouteImport } from './routes/fabrication'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as InstallationRouteImport } from './routes/installation'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Lookahead10dRouteImport } from './routes/lookahead-10d'
import { Route as Lookahead48hRouteImport } from './routes/lookahead-48h'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RfisRouteImport } from './routes/rfis'
import { Route as RoadblocksRouteImport } from './routes/roadblocks'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SmartListsRouteImport } from './routes/smart-lists'
import { Route as SubmittalsRouteImport } from './routes/submittals'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WorkPackagesRouteImport } from './routes/work-packages'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPmWorkspaceRouteImport } from './routes/api/pm/workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsRoute = DrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricationRoute = FabricationRouteImport.update({
  id: '/fabrication',
  path: '/fabrication',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationRoute = InstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Lookahead10dRoute = Lookahead10dRouteImport.update({
  id: '/lookahead-10d',
  path: '/lookahead-10d',
  getParentRoute: () => rootRouteImport,
} as any)
const Lookahead48hRoute = Lookahead48hRouteImport.update({
  id: '/lookahead-48h',
  path: '/lookahead-48h',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RfisRoute = RfisRouteImport.update({
  id: '/rfis',
  path: '/rfis',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadblocksRoute = RoadblocksRouteImport.update({
  id: '/roadblocks',
  path: '/roadblocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartListsRoute = SmartListsRouteImport.update({
  id: '/smart-lists',
  path: '/smart-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittalsRoute = SubmittalsRouteImport.update({
  id: '/submittals',
  path: '/submittals',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPackagesRoute = WorkPackagesRouteImport.update({
  id: '/work-packages',
  path: '/work-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPmWorkspaceRoute = ApiPmWorkspaceRouteImport.update({
  id: '/api/pm/workspace',
  path: '/api/pm/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/calendar': typeof CalendarRoute
  '/changes': typeof ChangesRoute
  '/daily': typeof DailyRoute
  '/delivery': typeof DeliveryRoute
  '/drawings': typeof DrawingsRoute
  '/fabrication': typeof FabricationRoute
  '/inbox': typeof InboxRoute
  '/installation': typeof InstallationRoute
  '/journal': typeof JournalRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/lookahead-10d': typeof Lookahead10dRoute
  '/lookahead-48h': typeof Lookahead48hRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/projects': typeof ProjectsRoute
  '/rfis': typeof RfisRoute
  '/roadblocks': typeof RoadblocksRoute
  '/search': typeof SearchRoute
  '/smart-lists': typeof SmartListsRoute
  '/submittals': typeof SubmittalsRoute
  '/tags': typeof TagsRoute
  '/tasks': typeof TasksRoute
  '/timeline': typeof TimelineRoute
  '/work-packages': typeof WorkPackagesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pm/workspace': typeof ApiPmWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/calendar': typeof CalendarRoute
  '/changes': typeof ChangesRoute
  '/daily': typeof DailyRoute
  '/delivery': typeof DeliveryRoute
  '/drawings': typeof DrawingsRoute
  '/fabrication': typeof FabricationRoute
  '/inbox': typeof InboxRoute
  '/installation': typeof InstallationRoute
  '/journal': typeof JournalRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/lookahead-10d': typeof Lookahead10dRoute
  '/lookahead-48h': typeof Lookahead48hRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/projects': typeof ProjectsRoute
  '/rfis': typeof RfisRoute
  '/roadblocks': typeof RoadblocksRoute
  '/search': typeof SearchRoute
  '/smart-lists': typeof SmartListsRoute
  '/submittals': typeof SubmittalsRoute
  '/tags': typeof TagsRoute
  '/tasks': typeof TasksRoute
  '/timeline': typeof TimelineRoute
  '/work-packages': typeof WorkPackagesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pm/workspace': typeof ApiPmWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/calendar': typeof CalendarRoute
  '/changes': typeof ChangesRoute
  '/daily': typeof DailyRoute
  '/delivery': typeof DeliveryRoute
  '/drawings': typeof DrawingsRoute
  '/fabrication': typeof FabricationRoute
  '/inbox': typeof InboxRoute
  '/installation': typeof InstallationRoute
  '/journal': typeof JournalRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/lookahead-10d': typeof Lookahead10dRoute
  '/lookahead-48h': typeof Lookahead48hRoute
  '/notes': typeof NotesRoute
  '/planner': typeof PlannerRoute
  '/projects': typeof ProjectsRoute
  '/rfis': typeof RfisRoute
  '/roadblocks': typeof RoadblocksRoute
  '/search': typeof SearchRoute
  '/smart-lists': typeof SmartListsRoute
  '/submittals': typeof SubmittalsRoute
  '/tags': typeof TagsRoute
  '/tasks': typeof TasksRoute
  '/timeline': typeof TimelineRoute
  '/work-packages': typeof WorkPackagesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pm/workspace': typeof ApiPmWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/calendar'
    | '/changes'
    | '/daily'
    | '/delivery'
    | '/drawings'
    | '/fabrication'
    | '/inbox'
    | '/installation'
    | '/journal'
    | '/lists'
    | '/login'
    | '/lookahead-10d'
    | '/lookahead-48h'
    | '/notes'
    | '/planner'
    | '/projects'
    | '/rfis'
    | '/roadblocks'
    | '/search'
    | '/smart-lists'
    | '/submittals'
    | '/tags'
    | '/tasks'
    | '/timeline'
    | '/work-packages'
    | '/api/auth/$'
    | '/api/pm/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/calendar'
    | '/changes'
    | '/daily'
    | '/delivery'
    | '/drawings'
    | '/fabrication'
    | '/inbox'
    | '/installation'
    | '/journal'
    | '/lists'
    | '/login'
    | '/lookahead-10d'
    | '/lookahead-48h'
    | '/notes'
    | '/planner'
    | '/projects'
    | '/rfis'
    | '/roadblocks'
    | '/search'
    | '/smart-lists'
    | '/submittals'
    | '/tags'
    | '/tasks'
    | '/timeline'
    | '/work-packages'
    | '/api/auth/$'
    | '/api/pm/workspace'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/calendar'
    | '/changes'
    | '/daily'
    | '/delivery'
    | '/drawings'
    | '/fabrication'
    | '/inbox'
    | '/installation'
    | '/journal'
    | '/lists'
    | '/login'
    | '/lookahead-10d'
    | '/lookahead-48h'
    | '/notes'
    | '/planner'
    | '/projects'
    | '/rfis'
    | '/roadblocks'
    | '/search'
    | '/smart-lists'
    | '/submittals'
    | '/tags'
    | '/tasks'
    | '/timeline'
    | '/work-packages'
    | '/api/auth/$'
    | '/api/pm/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  CalendarRoute: typeof CalendarRoute
  ChangesRoute: typeof ChangesRoute
  DailyRoute: typeof DailyRoute
  DeliveryRoute: typeof DeliveryRoute
  DrawingsRoute: typeof DrawingsRoute
  FabricationRoute: typeof FabricationRoute
  InboxRoute: typeof InboxRoute
  InstallationRoute: typeof InstallationRoute
  JournalRoute: typeof JournalRoute
  ListsRoute: typeof ListsRoute
  LoginRoute: typeof LoginRoute
  Lookahead10dRoute: typeof Lookahead10dRoute
  Lookahead48hRoute: typeof Lookahead48hRoute
  NotesRoute: typeof NotesRoute
  PlannerRoute: typeof PlannerRoute
  ProjectsRoute: typeof ProjectsRoute
  RfisRoute: typeof RfisRoute
  RoadblocksRoute: typeof RoadblocksRoute
  SearchRoute: typeof SearchRoute
  SmartListsRoute: typeof SmartListsRoute
  SubmittalsRoute: typeof SubmittalsRoute
  TagsRoute: typeof TagsRoute
  TasksRoute: typeof TasksRoute
  TimelineRoute: typeof TimelineRoute
  WorkPackagesRoute: typeof WorkPackagesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPmWorkspaceRoute: typeof ApiPmWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings': {
      id: '/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrication': {
      id: '/fabrication'
      path: '/fabrication'
      fullPath: '/fabrication'
      preLoaderRoute: typeof FabricationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation': {
      id: '/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof InstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookahead-10d': {
      id: '/lookahead-10d'
      path: '/lookahead-10d'
      fullPath: '/lookahead-10d'
      preLoaderRoute: typeof Lookahead10dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookahead-48h': {
      id: '/lookahead-48h'
      path: '/lookahead-48h'
      fullPath: '/lookahead-48h'
      preLoaderRoute: typeof Lookahead48hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfis': {
      id: '/rfis'
      path: '/rfis'
      fullPath: '/rfis'
      preLoaderRoute: typeof RfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadblocks': {
      id: '/roadblocks'
      path: '/roadblocks'
      fullPath: '/roadblocks'
      preLoaderRoute: typeof RoadblocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-lists': {
      id: '/smart-lists'
      path: '/smart-lists'
      fullPath: '/smart-lists'
      preLoaderRoute: typeof SmartListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submittals': {
      id: '/submittals'
      path: '/submittals'
      fullPath: '/submittals'
      preLoaderRoute: typeof SubmittalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-packages': {
      id: '/work-packages'
      path: '/work-packages'
      fullPath: '/work-packages'
      preLoaderRoute: typeof WorkPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pm/workspace': {
      id: '/api/pm/workspace'
      path: '/api/pm/workspace'
      fullPath: '/api/pm/workspace'
      preLoaderRoute: typeof ApiPmWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  CalendarRoute: CalendarRoute,
  ChangesRoute: ChangesRoute,
  DailyRoute: DailyRoute,
  DeliveryRoute: DeliveryRoute,
  DrawingsRoute: DrawingsRoute,
  FabricationRoute: FabricationRoute,
  InboxRoute: InboxRoute,
  InstallationRoute: InstallationRoute,
  JournalRoute: JournalRoute,
  ListsRoute: ListsRoute,
  LoginRoute: LoginRoute,
  Lookahead10dRoute: Lookahead10dRoute,
  Lookahead48hRoute: Lookahead48hRoute,
  NotesRoute: NotesRoute,
  PlannerRoute: PlannerRoute,
  ProjectsRoute: ProjectsRoute,
  RfisRoute: RfisRoute,
  RoadblocksRoute: RoadblocksRoute,
  SearchRoute: SearchRoute,
  SmartListsRoute: SmartListsRoute,
  SubmittalsRoute: SubmittalsRoute,
  TagsRoute: TagsRoute,
  TasksRoute: TasksRoute,
  TimelineRoute: TimelineRoute,
  WorkPackagesRoute: WorkPackagesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPmWorkspaceRoute: ApiPmWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
