/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DrawingsRouteImport } from './routes/drawings'
import { Route as FabricationRouteImport } from './routes/fabrication'
import { Route as InstallationRouteImport } from './routes/installation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Lookahead10dRouteImport } from './routes/lookahead-10d'
import { Route as Lookahead48hRouteImport } from './routes/lookahead-48h'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RfisRouteImport } from './routes/rfis'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPmWorkspaceRouteImport } from './routes/api/pm/workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsRoute = DrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricationRoute = FabricationRouteImport.update({
  id: '/fabrication',
  path: '/fabrication',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationRoute = InstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Lookahead10dRoute = Lookahead10dRouteImport.update({
  id: '/lookahead-10d',
  path: '/lookahead-10d',
  getParentRoute: () => rootRouteImport,
} as any)
const Lookahead48hRoute = Lookahead48hRouteImport.update({
  id: '/lookahead-48h',
  path: '/lookahead-48h',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RfisRoute = RfisRouteImport.update({
  id: '/rfis',
  path: '/rfis',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPmWorkspaceRoute = ApiPmWorkspaceRouteImport.update({
  id: '/api/pm/workspace',
  path: '/api/pm/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/calendar': typeof CalendarRoute
  '/changes': typeof ChangesRoute
  '/delivery': typeof DeliveryRoute
  '/drawings': typeof DrawingsRoute
  '/fabrication': typeof FabricationRoute
  '/installation': typeof InstallationRoute
  '/login': typeof LoginRoute
  '/lookahead-10d': typeof Lookahead10dRoute
  '/lookahead-48h': typeof Lookahead48hRoute
  '/projects': typeof ProjectsRoute
  '/rfis': typeof RfisRoute
  '/tasks': typeof TasksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pm/workspace': typeof ApiPmWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/calendar': typeof CalendarRoute
  '/changes': typeof ChangesRoute
  '/delivery': typeof DeliveryRoute
  '/drawings': typeof DrawingsRoute
  '/fabrication': typeof FabricationRoute
  '/installation': typeof InstallationRoute
  '/login': typeof LoginRoute
  '/lookahead-10d': typeof Lookahead10dRoute
  '/lookahead-48h': typeof Lookahead48hRoute
  '/projects': typeof ProjectsRoute
  '/rfis': typeof RfisRoute
  '/tasks': typeof TasksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pm/workspace': typeof ApiPmWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/calendar': typeof CalendarRoute
  '/changes': typeof ChangesRoute
  '/delivery': typeof DeliveryRoute
  '/drawings': typeof DrawingsRoute
  '/fabrication': typeof FabricationRoute
  '/installation': typeof InstallationRoute
  '/login': typeof LoginRoute
  '/lookahead-10d': typeof Lookahead10dRoute
  '/lookahead-48h': typeof Lookahead48hRoute
  '/projects': typeof ProjectsRoute
  '/rfis': typeof RfisRoute
  '/tasks': typeof TasksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pm/workspace': typeof ApiPmWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/calendar'
    | '/changes'
    | '/delivery'
    | '/drawings'
    | '/fabrication'
    | '/installation'
    | '/login'
    | '/lookahead-10d'
    | '/lookahead-48h'
    | '/projects'
    | '/rfis'
    | '/tasks'
    | '/api/auth/$'
    | '/api/pm/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/calendar'
    | '/changes'
    | '/delivery'
    | '/drawings'
    | '/fabrication'
    | '/installation'
    | '/login'
    | '/lookahead-10d'
    | '/lookahead-48h'
    | '/projects'
    | '/rfis'
    | '/tasks'
    | '/api/auth/$'
    | '/api/pm/workspace'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/calendar'
    | '/changes'
    | '/delivery'
    | '/drawings'
    | '/fabrication'
    | '/installation'
    | '/login'
    | '/lookahead-10d'
    | '/lookahead-48h'
    | '/projects'
    | '/rfis'
    | '/tasks'
    | '/api/auth/$'
    | '/api/pm/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  CalendarRoute: typeof CalendarRoute
  ChangesRoute: typeof ChangesRoute
  DeliveryRoute: typeof DeliveryRoute
  DrawingsRoute: typeof DrawingsRoute
  FabricationRoute: typeof FabricationRoute
  InstallationRoute: typeof InstallationRoute
  LoginRoute: typeof LoginRoute
  Lookahead10dRoute: typeof Lookahead10dRoute
  Lookahead48hRoute: typeof Lookahead48hRoute
  ProjectsRoute: typeof ProjectsRoute
  RfisRoute: typeof RfisRoute
  TasksRoute: typeof TasksRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPmWorkspaceRoute: typeof ApiPmWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings': {
      id: '/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrication': {
      id: '/fabrication'
      path: '/fabrication'
      fullPath: '/fabrication'
      preLoaderRoute: typeof FabricationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation': {
      id: '/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof InstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookahead-10d': {
      id: '/lookahead-10d'
      path: '/lookahead-10d'
      fullPath: '/lookahead-10d'
      preLoaderRoute: typeof Lookahead10dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookahead-48h': {
      id: '/lookahead-48h'
      path: '/lookahead-48h'
      fullPath: '/lookahead-48h'
      preLoaderRoute: typeof Lookahead48hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfis': {
      id: '/rfis'
      path: '/rfis'
      fullPath: '/rfis'
      preLoaderRoute: typeof RfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pm/workspace': {
      id: '/api/pm/workspace'
      path: '/api/pm/workspace'
      fullPath: '/api/pm/workspace'
      preLoaderRoute: typeof ApiPmWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  CalendarRoute: CalendarRoute,
  ChangesRoute: ChangesRoute,
  DeliveryRoute: DeliveryRoute,
  DrawingsRoute: DrawingsRoute,
  FabricationRoute: FabricationRoute,
  InstallationRoute: InstallationRoute,
  LoginRoute: LoginRoute,
  Lookahead10dRoute: Lookahead10dRoute,
  Lookahead48hRoute: Lookahead48hRoute,
  ProjectsRoute: ProjectsRoute,
  RfisRoute: RfisRoute,
  TasksRoute: TasksRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPmWorkspaceRoute: ApiPmWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
